In [2]:
import numpy as np
import time

In [3]:
a = np.zeros(4)
print(f"np.zeros(4) : a = {a}, shape = {a.shape}, data type = {a.dtype}")

np.zeros(4) : a = [0. 0. 0. 0.], shape = (4,), data type = float64


In [4]:
a = np.zeros((4,))
print(f"np.zeros((4,)) : a = {a}, shape = {a.shape}, data type = {a.dtype}")

np.zeros((4,)) : a = [0. 0. 0. 0.], shape = (4,), data type = float64


In [5]:
a = np.random.random_sample(4)
print(f"np.random.random_sample(4) : a = {a}, shape = {a.shape}, data type = {a.dtype}")

np.random.random_sample(4) : a = [0.46276143 0.94902747 0.95146206 0.07629531], shape = (4,), data type = float64


In [6]:
a = np.arange(4)
print(f"np.arange(4) : a = {a}, shape = {a.shape}, data type = {a.dtype}")

np.arange(4) : a = [0 1 2 3], shape = (4,), data type = int64


In [8]:
a = np.arange(4.)
print(f"np.arange(4) : a = {a}, shape = {a.shape}, data type = {a.dtype}")

np.arange(4) : a = [0. 1. 2. 3.], shape = (4,), data type = float64


In [7]:
a = np.random.rand(4)
print(f"np.random.rand(4) : a = {a}, shape = {a.shape}, data type = {a.dtype}")

np.random.rand(4) : a = [0.83312664 0.10429462 0.89082732 0.66069707], shape = (4,), data type = float64


In [9]:
a = np.array([4, 6, 2, 9])
print(f"np.array([4, 6, 2, 9]) : a = {a}, shape = {a.shape}, data type = {a.dtype}")

np.array([4, 6, 2, 9]) : a = [4 6 2 9], shape = (4,), data type = int64


In [10]:
a = np.array([4, 6., 2, 9])
print(f"np.array([4, 6., 2, 9]) : a = {a}, shape = {a.shape}, data type = {a.dtype}")

np.array([4, 6., 2, 9]) : a = [4. 6. 2. 9.], shape = (4,), data type = float64


In [16]:
# some
b = np.zeros((4,5))
print(f"np.zeros((4,5.)) : b = {b}, shape = {b.shape}, data type = {b.dtype}")

np.zeros((4,5.)) : b = [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape = (4, 5), data type = float64


In [20]:
a = np.arange(10)
print(a)

print(f"a[2].shape = {a[2].shape}, a[2] = {a[2]} : scalar!")

print(a[-1])

try:
    c = a[66]
except Exception as e:
    print("error : ")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape = (), a[2] = 2 : scalar!
9
error : 
index 66 is out of bounds for axis 0 with size 10


In [25]:
# slicing: you already know this man! however:

a = np.arange(10)
print(f"a          = {a}")
s = a[2:7:1];   print(f"s          = {s}")

s = a[2:7:2];     print("a[2:7:2] = ", s)

s = a[3:];        print("a[3:]    = ", s)

s = a[:3];        print("a[:3]    = ", s)

s = a[:];         print("a[:]     = ", s)

a          = [0 1 2 3 4 5 6 7 8 9]
s          = [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


In [8]:
a = np.array([2, 3, 5, 7, 11])

print(f"a = {a}")

b = -a
print(f"b = -a = {b}")

sum = np.sum(a);
print(f"np.sum(a) = {sum}")

mean = np.mean(a)
print(f"np.mean(a) = {mean} and 28/5 = {28/5}")

b = a ** 2
print(f"a**2 = {b}")

a = [ 2  3  5  7 11]
b = -a = [ -2  -3  -5  -7 -11]
np.sum(a) = 28
np.mean(a) = 5.6 and 28/5 = 5.6
a**2 = [  4   9  25  49 121]


In [9]:
a = np.array([1, 2, 3])
b = np.array([-1, -2, -3])
print(f"a + b = {a + b}")

a + b = [0 0 0]


In [10]:
c = np.array([2, 6])
print(f"a + c = {a + c}")

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [11]:
a = np.array([1, 2, 3])
b = 5 * a
c = a * 5
print(f"b = 5*a = {b} and c = a*5 = {c}")

b = 5*a = [ 5 10 15] and c = a*5 = [ 5 10 15]


In [17]:
def dot_product(a, b):
    n = a.shape[0]
    res = 0
    for i in range(n):
        res += (a[i] * b[i])
    
    return res

In [18]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
print(f"dot_product(a, b) = {dot_product(a, b)}")

dot_product(a, b) = 14


In [19]:
print(np.dot(a, b))

14


In [20]:
# speed : 
np.random.seed(1)

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()
c = dot_product(a, b)
toc = time.time()

print(f"dot_product(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  249825.0234
Vectorized version duration: 3.6283 ms 
dot_product(a, b) =  249825.0234
loop version duration: 406.5936 ms 


In [23]:
X = np.array([[1], [2], [3], [4]])
w = np.array([2])
c = np.dot(w, X[1])
print(c)

4


In [26]:
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}, a = {a}")                     

a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.random_sample((3, 4))  
print(f"a shape = {a.shape}, a = {a}") 

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (3, 4), a = [[0.5251306  0.16184726 0.39912314 0.76850178]
 [0.90838834 0.54804153 0.89855918 0.03513744]
 [0.09212483 0.86121123 0.50516394 0.9481497 ]]


In [27]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([[5], [4], [3]]);   print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],   # One can also
              [4],   # separate values
              [3]]); #into separate rows
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


In [29]:
#vector indexing operations on matrices
a = np.arange(6).reshape(-1, 2)   #reshape is a convenient way to create matrices
print(f"a.shape: {a.shape}, \na= {a}")

print(f"a[2][0] = {a[2][0]}") #good

#access an element
print(f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]},     type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")

#access a row
print(f"a[2].shape:   {a[2].shape}, a[2]   = {a[2]}, type(a[2])   = {type(a[2])}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]
a[2][0] = 4

a[2,0].shape:   (), a[2,0] = 4,     type(a[2,0]) = <class 'numpy.int64'> Accessing an element returns a scalar

a[2].shape:   (2,), a[2]   = [4 5], type(a[2])   = <class 'numpy.ndarray'>


In [30]:
#vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")


a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array
